# Generated by Django 2.1.5 on 2019-01-15 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0002_auto_20190115_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarinfo',
            old_name='user',
            new_name='userID',
        ),
    ]
