# Generated by Django 2.1.5 on 2019-01-16 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_friends', to='accounts.Accounts')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_friends', to='accounts.Accounts')),
            ],
        ),
    ]
