# Generated by Django 2.1.5 on 2019-01-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thisday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.TextField()),
                ('leaderID', models.TextField()),
                ('memberID', models.TextField()),
                ('date', models.DateTimeField()),
                ('month', models.DateTimeField()),
                ('year', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.TextField()),
                ('date', models.DateTimeField()),
                ('month', models.DateTimeField()),
                ('year', models.DateTimeField()),
            ],
        ),
    ]
