# Generated by Django 2.1.5 on 2019-01-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thisday', '0003_auto_20190114_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
