# Generated by Django 2.1.5 on 2019-01-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thisday', '0005_auto_20190115_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='memberList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thisday.Members'),
        ),
    ]
