# Generated by Django 2.1.5 on 2019-01-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thisday', '0006_auto_20190115_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupinfo',
            old_name='FixedSchedule',
            new_name='fixedSchedule',
        ),
    ]
