# Generated by Django 2.1.5 on 2019-01-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thisday', '0007_auto_20190115_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='fixedSchedule',
            field=models.DateTimeField(),
        ),
    ]
