# Generated by Django 2.1.5 on 2019-01-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thisday', '0008_auto_20190115_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendsList',
        ),
    ]
