# Generated by Django 2.1.5 on 2019-01-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thisday', '0009_delete_friendslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupinfo',
            name='memberList',
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='memberList',
            field=models.ManyToManyField(to='thisday.Members'),
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='dateList',
            field=models.ManyToManyField(to='thisday.DateList'),
        ),
    ]
