# Generated by Django 2.1.5 on 2019-01-17 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friendship'),
        ('thisday', '0010_auto_20190116_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votingDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupinfo',
            name='dateList',
        ),
        migrations.RemoveField(
            model_name='members',
            name='userID',
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='finalDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='members',
            name='member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='my_friends', to='accounts.Friendship'),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='DateList',
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='voteList',
            field=models.ManyToManyField(to='thisday.VoteInfo'),
        ),
    ]
