# Generated by Django 2.1.5 on 2019-01-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friendship'),
        ('thisday', '0013_auto_20190118_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinfo',
            name='memberList',
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='member1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='accounts.Accounts'),
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='member2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='accounts.Accounts'),
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='member3',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='member3', to='accounts.Accounts'),
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='member4',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='member4', to='accounts.Accounts'),
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='member5',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='member5', to='accounts.Accounts'),
        ),
    ]
