# Generated by Django 2.1.5 on 2019-01-18 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thisday', '0014_auto_20190118_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='finalDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='fixedSchedule',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='vote1',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='vote2',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='vote3',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='vote4',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='vote5',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
